<<<<<<< HEAD
# Generated by Django 5.1.4 on 2025-01-04 20:30

=======
>>>>>>> 68cdfb849ce52235a489914a0e13f457e181b026
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('name', models.CharField(max_length=255)),
                ('genres', models.CharField(max_length=255)),
                ('directed', models.CharField(max_length=255)),
                ('producers', models.CharField(max_length=255)),
                ('screenwriters', models.CharField(max_length=255)),
                ('cinematographer', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
=======
                ('Genres', models.CharField(max_length=255)),
                ('Directed', models.CharField(max_length=255)),
                ('Producers', models.CharField(max_length=255)),
                ('Screenwriters', models.CharField(max_length=255)),
                ('Cinematographer', models.CharField(max_length=255)),
                ('Year', models.IntegerField )
>>>>>>> 68cdfb849ce52235a489914a0e13f457e181b026
            ],
        ),
    ]
