# Generated by Django 5.1.4 on 2025-01-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='film_images/'),
        ),
        migrations.AlterField(
            model_name='film',
            name='cinematographer',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='film',
            name='directed',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='film',
            name='genres',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='film',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='film',
            name='producers',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='film',
            name='screenwriters',
            field=models.CharField(max_length=200),
        ),
    ]
