# Generated by Django 5.1.4 on 2025-01-05 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0003_rename_name_film_title_film_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='description',
        ),
        migrations.RemoveField(
            model_name='film',
            name='title',
        ),
        migrations.AddField(
            model_name='film',
            name='name',
            field=models.CharField(default='Untitled', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='film',
            name='cinematographer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='film',
            name='directed',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='film',
            name='genres',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='film',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='films/images/'),
        ),
        migrations.AlterField(
            model_name='film',
            name='producers',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='film',
            name='screenwriters',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='film',
            name='year',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
    ]
