# Generated by Django 5.1.4 on 2025-01-13 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0004_remove_film_description_remove_film_title_film_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='cinematographer',
        ),
        migrations.RemoveField(
            model_name='film',
            name='producers',
        ),
        migrations.RemoveField(
            model_name='film',
            name='screenwriters',
        ),
        migrations.AlterField(
            model_name='film',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='film/media/images'),
        ),
    ]
