# Generated by Django 5.1.4 on 2025-01-24 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0006_remove_film_image_film_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
